export interface Person {
  id: number
  nameArabic: string
  nameEnglish: string
  age?: number
  description?: string
  isProphet: boolean
  relation?: string // Relationship type (son, daughter, wife, etc.)
  miracles?: string[]
  family?: {
    father?: string
    mother?: string
    wives?: string[]
    children?: string[]
    siblings?: string[]
    other?: string
  }
  position: {
    x: number
    y: number
  }
  connections: number[]
}

export type Prophet = Person & { isProphet: true }

export const people: Person[] = [
  // Generation 1: Adam and Eve
  {
    id: 1,
    nameArabic: "آدم",
    nameEnglish: "Adam",
    age: 930,
    description: "أول إنسان ونبي، خلقه الله من طين.",
    isProphet: true,
    miracles: ["منحه الله معرفة أسماء كل شيء", "قدرته على تسمية الأشياء"],
    family: {
      wives: ["حواء (Eve)"],
      children: ["قابيل (Cain)", "هابيل (Abel)", "شيث (Seth)", "وآخرون"],
    },
    position: { x: 100, y: 180 },
    connections: [101, 102, 103, 104, 2],
  },
  {
    id: 101,
    nameArabic: "حواء",
    nameEnglish: "Eve",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة آدم وأم البشرية",
    position: { x: 140, y: 180 },
    connections: [102, 103, 104],
  },
  {
    id: 102,
    nameArabic: "قابيل",
    nameEnglish: "Cain",
    isProphet: false,
    relation: "ابن",
    description: "ابن آدم وحواء",
    position: { x: 60, y: 150 },
    connections: [],
  },
  {
    id: 103,
    nameArabic: "هابيل",
    nameEnglish: "Abel",
    isProphet: false,
    relation: "ابن",
    description: "ابن آدم وحواء",
    position: { x: 100, y: 150 },
    connections: [],
  },
  {
    id: 104,
    nameArabic: "شيث",
    nameEnglish: "Seth",
    isProphet: false,
    relation: "ابن",
    description: "ابن آدم وحواء",
    position: { x: 140, y: 150 },
    connections: [2],
  },

  // Generation 2: Idris
  {
    id: 2,
    nameArabic: "إدريس",
    nameEnglish: "Idris",
    age: 356,
    description: "يُعرف بأخنوخ؛ اشتهر بحكمته وتفانيه.",
    isProphet: true,
    miracles: ["يعتقد أنه أول من كتب بالقلم", "امتلاك معرفة عميقة"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع في النصوص الإسلامية",
    },
    position: { x: 100, y: 120 },
    connections: [3],
  },

  // Generation 3: Nuh and family
  {
    id: 3,
    nameArabic: "نوح",
    nameEnglish: "Nuh",
    age: 1450,
    description: "المعروف بنوح؛ دعا إلى التوحيد لقرون.",
    isProphet: true,
    miracles: ["بنى الفلك ونجا من الطوفان العظيم"],
    family: {
      sons: ["سام", "حام", "يافث", "يام (الذي لم يؤمن)"],
      other: "زوجته لم تؤمن برسالته",
    },
    position: { x: 100, y: 90 },
    connections: [105, 106, 107, 108, 109, 4, 5, 6],
  },
  {
    id: 105,
    nameArabic: "زوجة نوح",
    nameEnglish: "Noah's Wife",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة نوح التي لم تؤمن برسالته",
    position: { x: 140, y: 90 },
    connections: [],
  },
  {
    id: 106,
    nameArabic: "سام",
    nameEnglish: "Shem",
    isProphet: false,
    relation: "ابن",
    description: "ابن نوح، أبو الساميين",
    position: { x: 60, y: 70 },
    connections: [6],
  },
  {
    id: 107,
    nameArabic: "حام",
    nameEnglish: "Ham",
    isProphet: false,
    relation: "ابن",
    description: "ابن نوح",
    position: { x: 90, y: 70 },
    connections: [],
  },
  {
    id: 108,
    nameArabic: "يافث",
    nameEnglish: "Japheth",
    isProphet: false,
    relation: "ابن",
    description: "ابن نوح",
    position: { x: 120, y: 70 },
    connections: [],
  },
  {
    id: 109,
    nameArabic: "يام",
    nameEnglish: "Yam",
    isProphet: false,
    relation: "ابن",
    description: "ابن نوح الذي لم يؤمن وغرق في الطوفان",
    position: { x: 150, y: 70 },
    connections: [],
  },

  // Prophets after Nuh
  {
    id: 4,
    nameArabic: "هود",
    nameEnglish: "Hud",
    age: 165,
    description: "أُرسل إلى قوم عاد لهدايتهم.",
    isProphet: true,
    miracles: ["نجا من عاصفة مدمرة أهلكت الكافرين"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 30, y: 60 },
    connections: [],
  },
  {
    id: 5,
    nameArabic: "صالح",
    nameEnglish: "Salih",
    age: 180,
    description: "أُرسل إلى قوم ثمود لدعوتهم إلى التوحيد.",
    isProphet: true,
    miracles: ["أخرج ناقة من صخرة كآية"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 65, y: 60 },
    connections: [],
  },

  // Ibrahim and family
  {
    id: 6,
    nameArabic: "إبراهيم",
    nameEnglish: "Ibrahim",
    age: 195,
    description: "المعروف بإبراهيم؛ أب الأنبياء في الإسلام والمسيحية واليهودية.",
    isProphet: true,
    miracles: ["نجا من إلقائه في النار", "رُزق بأبناء في سن متقدمة"],
    family: {
      wives: ["سارة", "هاجر"],
      sons: ["إسماعيل", "إسحاق"],
    },
    position: { x: 100, y: 60 },
    connections: [7, 110, 111, 8, 9],
  },
  {
    id: 110,
    nameArabic: "سارة",
    nameEnglish: "Sarah",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة إبراهيم وأم إسحاق",
    position: { x: 135, y: 60 },
    connections: [9],
  },
  {
    id: 111,
    nameArabic: "هاجر",
    nameEnglish: "Hagar",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة إبراهيم وأم إسماعيل",
    position: { x: 170, y: 60 },
    connections: [8],
  },
  {
    id: 7,
    nameArabic: "لوط",
    nameEnglish: "Lut",
    age: 0,
    description: "المعروف بلوط؛ ابن أخ إبراهيم؛ أُرسل إلى مدن سدوم وعمورة.",
    isProphet: true,
    miracles: ["حذر قومه من العقاب الإلهي الوشيك"],
    family: {
      other: "زوجته لم تؤمن وعوقبت، وله ابنتان نجتا",
    },
    position: { x: 30, y: 40 },
    connections: [112, 113, 114],
  },
  {
    id: 112,
    nameArabic: "زوجة لوط",
    nameEnglish: "Lot's Wife",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة لوط التي لم تؤمن وهلكت",
    position: { x: 10, y: 40 },
    connections: [],
  },
  {
    id: 113,
    nameArabic: "ابنة لوط الأولى",
    nameEnglish: "Lot's First Daughter",
    isProphet: false,
    relation: "ابنة",
    description: "إحدى ابنتي لوط اللتين نجتا",
    position: { x: 20, y: 25 },
    connections: [],
  },
  {
    id: 114,
    nameArabic: "ابنة لوط الثانية",
    nameEnglish: "Lot's Second Daughter",
    isProphet: false,
    relation: "ابنة",
    description: "إحدى ابنتي لوط اللتين نجتا",
    position: { x: 40, y: 25 },
    connections: [],
  },

  // Ismail and descendants
  {
    id: 8,
    nameArabic: "إسماعيل",
    nameEnglish: "Isma'il",
    age: 137,
    description: "المعروف بإسماعيل؛ ابن إبراهيم وهاجر؛ ارتبط ببناء الكعبة.",
    isProphet: true,
    relation: "ابن",
    miracles: ["أحداث حياته يتم إحياؤها خلال مناسك الحج"],
    family: {
      father: "إبراهيم",
      mother: "هاجر",
      other: "تزوج من قبيلة جرهم، وله اثنا عشر ابناً",
    },
    position: { x: 170, y: 40 },
    connections: [115, 12, 25],
  },
  {
    id: 115,
    nameArabic: "زوجة إسماعيل",
    nameEnglish: "Ishmael's Wife",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة إسماعيل من قبيلة جرهم",
    position: { x: 200, y: 40 },
    connections: [],
  },

  // Ishaq and descendants
  {
    id: 9,
    nameArabic: "إسحاق",
    nameEnglish: "Ishaq",
    age: 180,
    description: "المعروف بإسحاق؛ ابن إبراهيم وسارة؛ والد يعقوب.",
    isProphet: true,
    relation: "ابن",
    miracles: ["وُلد لوالدين في سن الشيخوخة تحقيقاً للوعد الإلهي"],
    family: {
      father: "إبراهيم",
      mother: "سارة",
      wife: "رفقة",
      sons: ["عيسو", "يعقوب"],
    },
    position: { x: 100, y: 40 },
    connections: [116, 117, 10],
  },
  {
    id: 116,
    nameArabic: "رفقة",
    nameEnglish: "Rebecca",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة إسحاق وأم يعقوب وعيسو",
    position: { x: 135, y: 40 },
    connections: [10, 117],
  },
  {
    id: 117,
    nameArabic: "عيسو",
    nameEnglish: "Esau",
    isProphet: false,
    relation: "ابن",
    description: "ابن إسحاق وأخو يعقوب",
    position: { x: 70, y: 30 },
    connections: [],
  },

  // Yaqub and family
  {
    id: 10,
    nameArabic: "يعقوب",
    nameEnglish: "Ya'qub",
    age: 144,
    description: "المعروف بيعقوب؛ يُدعى أيضاً إسرائيل؛ أب الأسباط الاثني عشر.",
    isProphet: true,
    relation: "ابن",
    miracles: ["كانت له رؤى وأحلام؛ نسله أدى إلى العديد من الأنبياء"],
    family: {
      father: "إسحاق",
      wives: ["ليئة", "راحيل", "وأخريات"],
      sons: ["روبين", "شمعون", "لاوي", "يهوذا", "دان", "نفتالي", "جاد", "أشير", "يساكر", "زبولون", "يوسف", "بنيامين"],
    },
    position: { x: 100, y: 25 },
    connections: [118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 11, 128],
  },
  {
    id: 118,
    nameArabic: "ليئة",
    nameEnglish: "Leah",
    isProphet: false,
    relation: "زوجة",
    description: "إحدى زوجات يعقوب",
    position: { x: 65, y: 25 },
    connections: [120, 121, 122, 123, 126, 127],
  },
  {
    id: 119,
    nameArabic: "راحيل",
    nameEnglish: "Rachel",
    isProphet: false,
    relation: "زوجة",
    description: "إحدى زوجات يعقوب وأم يوسف وبنيامين",
    position: { x: 135, y: 25 },
    connections: [11, 128],
  },
  // First 6 sons of Yaqub
  {
    id: 120,
    nameArabic: "روبين",
    nameEnglish: "Reuben",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة، أكبر أبناء يعقوب",
    position: { x: 10, y: 15 },
    connections: [],
  },
  {
    id: 121,
    nameArabic: "شمعون",
    nameEnglish: "Simeon",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة",
    position: { x: 30, y: 15 },
    connections: [],
  },
  {
    id: 122,
    nameArabic: "لاوي",
    nameEnglish: "Levi",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة",
    position: { x: 50, y: 15 },
    connections: [],
  },
  {
    id: 123,
    nameArabic: "يهوذا",
    nameEnglish: "Judah",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة",
    position: { x: 70, y: 15 },
    connections: [],
  },
  {
    id: 124,
    nameArabic: "دان",
    nameEnglish: "Dan",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وبلهة جارية راحيل",
    position: { x: 90, y: 15 },
    connections: [],
  },
  {
    id: 125,
    nameArabic: "نفتالي",
    nameEnglish: "Naphtali",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وبلهة جارية راحيل",
    position: { x: 110, y: 15 },
    connections: [],
  },
  // More sons of Yaqub
  {
    id: 126,
    nameArabic: "يساكر",
    nameEnglish: "Issachar",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة",
    position: { x: 130, y: 15 },
    connections: [],
  },
  {
    id: 127,
    nameArabic: "زبولون",
    nameEnglish: "Zebulun",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وليئة",
    position: { x: 150, y: 15 },
    connections: [],
  },
  {
    id: 128,
    nameArabic: "بنيامين",
    nameEnglish: "Benjamin",
    isProphet: false,
    relation: "ابن",
    description: "ابن يعقوب وراحيل، أخو يوسف",
    position: { x: 170, y: 15 },
    connections: [],
  },

  // Yusuf
  {
    id: 11,
    nameArabic: "يوسف",
    nameEnglish: "Yusuf",
    age: 110,
    description: "المعروف بيوسف؛ اشتهر بجماله ونزاهته.",
    isProphet: true,
    relation: "ابن",
    miracles: ["تفسير الأحلام؛ ارتقى إلى السلطة في مصر"],
    family: {
      father: "يعقوب",
      mother: "راحيل",
      siblings: ["بنيامين وإخوته العشرة الآخرين"],
      wives: ["زليخة (أسينات)"],
      children: ["منسى", "أفرايم"],
    },
    position: { x: 100, y: 5 },
    connections: [129, 130, 131],
  },
  {
    id: 129,
    nameArabic: "زليخة",
    nameEnglish: "Zulaikha",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة يوسف (تُعرف أيضاً باسم أسينات)",
    position: { x: 70, y: 5 },
    connections: [130, 131],
  },
  {
    id: 130,
    nameArabic: "منسى",
    nameEnglish: "Manasseh",
    isProphet: false,
    relation: "ابن",
    description: "ابن يوسف",
    position: { x: 60, y: -5 },
    connections: [],
  },
  {
    id: 131,
    nameArabic: "أفرايم",
    nameEnglish: "Ephraim",
    isProphet: false,
    relation: "ابن",
    description: "ابن يوسف",
    position: { x: 80, y: -5 },
    connections: [],
  },

  // Shuayb
  {
    id: 12,
    nameArabic: "شعيب",
    nameEnglish: "Shu'ayb",
    age: 254,
    description: "أُرسل إلى أهل مدين وأصحاب الأيكة.",
    isProphet: true,
    miracles: ["حذر قومه من الغش في التجارة"],
    family: {
      daughters: ["صفورة وأخرى"],
    },
    position: { x: 170, y: 5 },
    connections: [132, 133],
  },
  {
    id: 132,
    nameArabic: "صفورة",
    nameEnglish: "Zipporah",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة شعيب وزوجة موسى",
    position: { x: 155, y: -5 },
    connections: [15],
  },
  {
    id: 133,
    nameArabic: "ابنة شعيب الأخرى",
    nameEnglish: "Shuayb's Other Daughter",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة شعيب الأخرى",
    position: { x: 185, y: -5 },
    connections: [],
  },

  // Ayyub
  {
    id: 13,
    nameArabic: "أيوب",
    nameEnglish: "Ayyub",
    age: 146,
    description: "المعروف بأيوب؛ مثال للصبر والإيمان خلال المحن.",
    isProphet: true,
    miracles: ["استعاد صحته وثروته بعد معاناة شديدة دون أن يفقد إيمانه"],
    family: {
      wife: "رحمة",
    },
    position: { x: 10, y: 5 },
    connections: [134],
  },
  {
    id: 134,
    nameArabic: "رحمة",
    nameEnglish: "Rahma",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة أيوب التي صبرت معه خلال محنته",
    position: { x: 10, y: -5 },
    connections: [],
  },

  // Dhul-Kifl
  {
    id: 14,
    nameArabic: "ذو الكفل",
    nameEnglish: "Dhul-Kifl",
    age: 0,
    description: "يُعرف عند البعض بحزقيال؛ اشتهر باستقامته وثباته.",
    isProphet: true,
    miracles: ["حافظ على الصبر وأقام العدل في جميع الظروف"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 40, y: -5 },
    connections: [],
  },

  // Musa and family
  {
    id: 15,
    nameArabic: "موسى",
    nameEnglish: "Musa",
    age: 123,
    description: "المعروف بموسى؛ قاد بني إسرائيل خارج مصر؛ تلقى التوراة.",
    isProphet: true,
    miracles: ["شق البحر الأحمر؛ تلقى الوصايا العشر؛ أظهر آيات عديدة أمام فرعون"],
    family: {
      brother: "هارون",
      sister: "مريم",
      wife: "صفورة بنت شعيب",
      children: ["جرشوم", "أليعازر"],
    },
    position: { x: 120, y: -15 },
    connections: [16, 135, 136, 137],
  },
  {
    id: 135,
    nameArabic: "مريم",
    nameEnglish: "Miriam",
    isProphet: false,
    relation: "أخت",
    description: "أخت موسى وهارون",
    position: { x: 100, y: -15 },
    connections: [],
  },
  {
    id: 136,
    nameArabic: "جرشوم",
    nameEnglish: "Gershom",
    isProphet: false,
    relation: "ابن",
    description: "ابن موسى وصفورة",
    position: { x: 110, y: -30 },
    connections: [],
  },
  {
    id: 137,
    nameArabic: "أليعازر",
    nameEnglish: "Eliezer",
    isProphet: false,
    relation: "ابن",
    description: "ابن موسى وصفورة",
    position: { x: 130, y: -30 },
    connections: [],
  },

  // Harun
  {
    id: 16,
    nameArabic: "هارون",
    nameEnglish: "Harun",
    age: 119,
    description: "المعروف بهارون؛ أخو موسى؛ عمل كمتحدث باسمه.",
    isProphet: true,
    relation: "أخ",
    miracles: ["ساعد موسى في نقل رسالة الله؛ لعب دوراً رئيسياً خلال الخروج"],
    family: {
      brother: "موسى",
      sister: "مريم",
      children: ["ناداب", "أبيهو", "ألعازار", "إيثامار"],
    },
    position: { x: 150, y: -15 },
    connections: [138, 139, 140, 141],
  },
  {
    id: 138,
    nameArabic: "ناداب",
    nameEnglish: "Nadab",
    isProphet: false,
    relation: "ابن",
    description: "ابن هارون",
    position: { x: 150, y: -30 },
    connections: [],
  },
  {
    id: 139,
    nameArabic: "أبيهو",
    nameEnglish: "Abihu",
    isProphet: false,
    relation: "ابن",
    description: "ابن هارون",
    position: { x: 170, y: -30 },
    connections: [],
  },
  {
    id: 140,
    nameArabic: "ألعازار",
    nameEnglish: "Eleazar",
    isProphet: false,
    relation: "ابن",
    description: "ابن هارون",
    position: { x: 190, y: -30 },
    connections: [],
  },
  {
    id: 141,
    nameArabic: "إيثامار",
    nameEnglish: "Ithamar",
    isProphet: false,
    relation: "ابن",
    description: "ابن هارون",
    position: { x: 210, y: -30 },
    connections: [],
  },

  // Dawud
  {
    id: 17,
    nameArabic: "داود",
    nameEnglish: "Dawud",
    age: 70,
    description: "المعروف بداود؛ ملك ونبي؛ اشتهر بمزاميره (الزبور).",
    isProphet: true,
    miracles: ["هزم جالوت؛ وُهب صوتاً جميلاً؛ الجبال والطيور شاركته في التسبيح"],
    family: {
      son: "سليمان",
      other: "له زوجات متعددة حسب تقاليد مختلفة",
    },
    position: { x: 60, y: -15 },
    connections: [18, 142],
  },
  {
    id: 142,
    nameArabic: "بتشبع",
    nameEnglish: "Bathsheba",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة داود وأم سليمان",
    position: { x: 50, y: -30 },
    connections: [18],
  },

  // Sulayman
  {
    id: 18,
    nameArabic: "سليمان",
    nameEnglish: "Sulayman",
    age: 180,
    description: "المعروف بسليمان؛ اشتهر بالحكمة وحكم مملكة واسعة.",
    isProphet: true,
    relation: "ابن",
    miracles: ["أمر الريح؛ تواصل مع الحيوانات؛ سيطر على الجن"],
    family: {
      father: "داود",
      other: "له زوجات متعددة حسب تقاليد مختلفة",
    },
    position: { x: 70, y: -30 },
    connections: [],
  },

  // Ilyas
  {
    id: 19,
    nameArabic: "إلياس",
    nameEnglish: "Ilyas",
    age: 0,
    description: "المعروف بإلياس؛ وعظ ضد عبادة بعل.",
    isProphet: true,
    miracles: ["أحيا الموتى؛ أنزل ناراً من السماء"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 20, y: -15 },
    connections: [20],
  },

  // Alyasa
  {
    id: 20,
    nameArabic: "اليسع",
    nameEnglish: "Alyasa",
    age: 0,
    description: "المعروف بإليشع؛ واصل عمل إلياس بين بني إسرائيل.",
    isProphet: true,
    miracles: ["شفى المرضى؛ أجرى معجزات متنوعة"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 30, y: -30 },
    connections: [],
  },

  // Yunus
  {
    id: 21,
    nameArabic: "يونس",
    nameEnglish: "Yunus",
    age: 0,
    description: "المعروف بيونان؛ دعا قومه إلى التوبة.",
    isProphet: true,
    miracles: ["نجا في بطن حوت كبير لمدة ثلاثة أيام"],
    family: {
      other: "تفاصيل عائلته غير مذكورة بشكل واسع",
    },
    position: { x: 10, y: -30 },
    connections: [],
  },

  // Zakariya and family
  {
    id: 22,
    nameArabic: "زكريا",
    nameEnglish: "Zakariya",
    age: 300,
    description: "المعروف بزكريا؛ كاهن متدين؛ كافل مريم.",
    isProphet: true,
    miracles: ["رُزق بابن، يحيى، في سن الشيخوخة"],
    family: {
      wife: "إليصابات",
      son: "يحيى",
    },
    position: { x: 200, y: 5 },
    connections: [23, 143, 144],
  },
  {
    id: 143,
    nameArabic: "إليصابات",
    nameEnglish: "Elizabeth",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة زكريا وأم يحيى",
    position: { x: 200, y: -5 },
    connections: [23],
  },
  {
    id: 144,
    nameArabic: "مريم",
    nameEnglish: "Mary",
    isProphet: false,
    relation: "مكفولة",
    description: "كفلها زكريا، أم عيسى، ولدته بمعجزة",
    position: { x: 230, y: -5 },
    connections: [24],
  },

  // Yahya
  {
    id: 23,
    nameArabic: "يحيى",
    nameEnglish: "Yahya",
    age: 95,
    description: "المعروف بيوحنا المعمدان؛ وعظ بالبر وعمّد المؤمنين.",
    isProphet: true,
    relation: "ابن",
    miracles: ["تعرف على قدوم عيسى وأعلن عنها"],
    family: {
      father: "زكريا",
      mother: "إليصابات",
    },
    position: { x: 200, y: -15 },
    connections: [],
  },

  // Isa
  {
    id: 24,
    nameArabic: "عيسى",
    nameEnglish: "Isa",
    age: 33,
    description: "المعروف بعيسى؛ وُلد بمعجزة لمريم؛ أجرى معجزات عديدة.",
    isProphet: true,
    miracles: ["تكلم وهو رضيع؛ شفى العميان والبرص؛ أحيا الموتى؛ خلق طيراً من الطين"],
    family: {
      mother: "مريم",
      other: "لا يُعرف له زوجة أو أطفال",
    },
    position: { x: 230, y: -15 },
    connections: [],
  },

  // Muhammad and family
  {
    id: 25,
    nameArabic: "محمد",
    nameEnglish: "Muhammad",
    age: 63,
    description:
      "النبي الأخير ورسول الإسلام؛ تلقى القرآن كوحي أخير. دعا إلى التوحيد والعدل والبر، وأسس مجتمعاً إسلامياً قوياً.",
    isProphet: true,
    miracles: [
      "القرآن، الذي يُعتبر معجزة خالدة",
      "انشقاق القمر",
      "تدفق الماء من بين أصابعه",
      "الإسراء والمعراج، حيث عرج إلى السماوات",
      "تنبأ بالعديد من الأحداث المستقبلية",
    ],
    family: {
      father: "عبد الله بن عبد المطلب",
      mother: "آمنة بنت وهب",
      other: "جده: عبد المطلب، عمه: أبو طالب",
      wives: [
        "خديجة بنت خويلد",
        "سودة بنت زمعة",
        "عائشة بنت أبي بكر",
        "حفصة بنت عمر",
        "زينب بنت خزيمة",
        "أم سلمة",
        "زينب بنت جحش",
        "جويرية بنت الحارث",
        "أم حبيبة",
        "صفية بنت حيي",
        "ميمونة بنت الحارث",
      ],
      children: ["القاسم", "عبد الله", "إبراهيم", "زينب", "رقية", "أم كلثوم", "فاطمة"],
    },
    position: { x: 250, y: -15 },
    connections: [145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162],
  },
  {
    id: 145,
    nameArabic: "عبد الله",
    nameEnglish: "Abdullah",
    isProphet: false,
    relation: "والد",
    description: "والد النبي محمد",
    position: { x: 230, y: 5 },
    connections: [],
  },
  {
    id: 146,
    nameArabic: "آمنة",
    nameEnglish: "Amina",
    isProphet: false,
    relation: "والدة",
    description: "والدة النبي محمد",
    position: { x: 250, y: 5 },
    connections: [],
  },
  {
    id: 147,
    nameArabic: "خديجة",
    nameEnglish: "Khadija",
    isProphet: false,
    relation: "زوجة",
    description: "أول زوجات النبي محمد وأم معظم أبنائه",
    position: { x: 270, y: 5 },
    connections: [153, 154, 155, 156, 157, 158],
  },
  {
    id: 148,
    nameArabic: "عائشة",
    nameEnglish: "Aisha",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة النبي محمد",
    position: { x: 290, y: 5 },
    connections: [],
  },
  {
    id: 149,
    nameArabic: "حفصة",
    nameEnglish: "Hafsa",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة النبي محمد",
    position: { x: 310, y: 5 },
    connections: [],
  },
  {
    id: 150,
    nameArabic: "أم سلمة",
    nameEnglish: "Umm Salama",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة النبي محمد",
    position: { x: 330, y: 5 },
    connections: [],
  },
  {
    id: 151,
    nameArabic: "زينب بنت جحش",
    nameEnglish: "Zaynab bint Jahsh",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة النبي محمد",
    position: { x: 350, y: 5 },
    connections: [],
  },
  {
    id: 152,
    nameArabic: "صفية",
    nameEnglish: "Safiyya",
    isProphet: false,
    relation: "زوجة",
    description: "زوجة النبي محمد",
    position: { x: 370, y: 5 },
    connections: [],
  },
  // Children of Muhammad
  {
    id: 153,
    nameArabic: "القاسم",
    nameEnglish: "Al-Qasim",
    isProphet: false,
    relation: "ابن",
    description: "ابن النبي محمد من خديجة",
    position: { x: 230, y: -30 },
    connections: [],
  },
  {
    id: 154,
    nameArabic: "عبد الله",
    nameEnglish: "Abdullah",
    isProphet: false,
    relation: "ابن",
    description: "ابن النبي محمد من خديجة",
    position: { x: 250, y: -30 },
    connections: [],
  },
  {
    id: 155,
    nameArabic: "زينب",
    nameEnglish: "Zaynab",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة النبي محمد من خديجة",
    position: { x: 270, y: -30 },
    connections: [],
  },
  {
    id: 156,
    nameArabic: "رقية",
    nameEnglish: "Ruqayya",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة النبي محمد من خديجة",
    position: { x: 290, y: -30 },
    connections: [],
  },
  {
    id: 157,
    nameArabic: "أم كلثوم",
    nameEnglish: "Umm Kulthum",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة النبي محمد من خديجة",
    position: { x: 310, y: -30 },
    connections: [],
  },
  {
    id: 158,
    nameArabic: "فاطمة",
    nameEnglish: "Fatima",
    isProphet: false,
    relation: "ابنة",
    description: "ابنة النبي محمد من خديجة",
    position: { x: 330, y: -30 },
    connections: [],
  },
  {
    id: 159,
    nameArabic: "إبراهيم",
    nameEnglish: "Ibrahim",
    isProphet: false,
    relation: "ابن",
    description: "ابن النبي محمد من مارية القبطية",
    position: { x: 350, y: -30 },
    connections: [],
  },
  {
    id: 160,
    nameArabic: "عبد المطلب",
    nameEnglish: "Abdul Muttalib",
    isProphet: false,
    relation: "جد",
    description: "جد النبي محمد",
    position: { x: 220, y: 15 },
    connections: [145],
  },
  {
    id: 161,
    nameArabic: "أبو طالب",
    nameEnglish: "Abu Talib",
    isProphet: false,
    relation: "عم",
    description: "عم النبي محمد وكافله بعد وفاة جده",
    position: { x: 240, y: 15 },
    connections: [],
  },
  {
    id: 162,
    nameArabic: "مارية القبطية",
    nameEnglish: "Maria al-Qibtiyya",
    isProphet: false,
    relation: "زوجة",
    description: "أم إبراهيم ابن النبي محمد",
    position: { x: 260, y: 15 },
    connections: [159],
  },
]

